### ISSUE TITLE
Not possible to use with Magento Cloud projects

### ISSUE THREAD

**Issue by behnamshayani** [fooman/composer-magento2-optimizations#1]
The plugin does not work with Magento cloud projects since they do not include either of:
`magento/project-community-edition` or `magento/project-enterprise-edition`
we are instead using `"magento/magento-cloud-metapackage": "2.3.1"`

**Comment by fooman** [comment]
@behnamshayani thanks for testing this out. I have added the cloud metapackage as an inbuilt option - see https://github.com/fooman/composer-magento2-optimizations/compare/7f83bd151323...4eb9ec51c1b2 

Please test and feel free to re-open the issue if it doesn't do the trick for you.

To note it is also possible to manually specify this in your root `composer.json` config like this

```json
{
  "extra": {
    "composer-magento2-optimizations": {
      "require": {
        "symfony/symfony": ">4.1"
      }
    }
  }
}
```
